<?php
/**
 * @var Application\Form\ResetPasswordForm $form
 */

$this->headTitle('Réinitialisation du mot de passe');
$form->prepare();
?>

<div class="row">
    <div class="banner col-md-12">
        <h2>Réinitialisez votre mot de passe</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="form-signin">
            <?php echo $this->form()->openTag($form) ?>

            <div class="form-group">
                <?php echo $this->formText($form->get('email')) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formPassword($form->get('password')) ?>
            </div>
            <div class="form-group">
                <?php echo $this->formPassword($form->get('passwordConfirmation')) ?>
            </div>
            <?php echo $this->formRow($form->get('submit')) ?>

            <?php echo $this->form()->closeTag() ?>
        </div>

        <hr/>

        <a href="<?php echo $this->url('connexion') ?>">Retour à la connexion</a>
    </div>
</div>
