<?php
/**
 * @var \Application\Entity\User $user
 * @var int $id
 */

/** @var Zend\Navigation\Page\Mvc $nav */
$nav = $this->navigation('Zend\Navigation\Utilisateur');
/** @var Zend\View\Helper\Navigation\Menu $menu */
$menu = $nav->menu();

if ($user->isDisabled()) {
    $menu->getContainer()->findOneBy('id', 'disable')->setVisible(false);
} else {
    $menu->getContainer()->findOneBy('id', 'enable')->setVisible(false);
}

/** @var Zend\Navigation\Page\Mvc $page */
foreach ($menu->getContainer() as $page) {
    $page->setParams(array('id' => $id));
}

$title = $nav->findOneBy('active', 1)->getTitle();
$this->headTitle($title);
?>

<div class="row">
    <div class="col-md-12 page-header tabbable-line">
        <?php echo $menu->setPartial('/layout/renderer/nav/header')->render() ?>
        <h1><?php echo $title ?></h1>
    </div>
</div>

<?php echo $this->partial('/layout/partial/flashmessenger') ?>