<?php
/** @var Zend\Navigation\Page\Mvc $nav */
$nav = $this->navigation('Zend\Navigation\Utilisateurs');
/** @var Zend\View\Helper\Navigation\Menu $menu */
$menu = $nav->menu();

/** @var Zend\Navigation\Page\Mvc $current */
$current = $nav->findOneBy('active', 1);
if ($current->getId() == 'index') {
    $current->setVisible(false);
} else {
    /** @var Zend\Navigation\Page\Mvc $page */
    foreach ($nav->getPages() as $page) {
        $page->setVisible(false);
    }

    $nav->findOneBy('id', 'index')->setVisible(true);
}
$title = $current->getTitle();

$this->headTitle($title);
?>

<div class="row">
    <div class="col-md-12 page-header tabbable-line">
        <?php echo $menu->setPartial('/layout/renderer/nav/header-list')->render() ?>
        <h1><?php echo $title ?></h1>
    </div>
</div>

<?php echo $this->partial('/layout/partial/flashmessenger') ?>