<?php
/** @var Zend\Navigation\Page\Mvc $nav */
$nav = $this->navigation('Zend\Navigation\Default');

$title = $nav->findOneBy('active', 1)->getTitle();
$this->headTitle($title);
?>

<div class="row">
    <div class="banner col-md-12">
        <img src="<?php echo $this->basePath('/img/logo-weprono.png') ?>" alt="We Prono"/>
        <h1><?php echo $title ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <?php echo $this->partial('/layout/partial/flashmessenger') ?>
    </div>
</div>
