<?php
/**
 * @var Zend\Navigation\Page\Mvc $page
 * @var Zend\Navigation\Page\Mvc $subPage
 *
 * @var int $id
 */
?>
<div class="links">
    <ul class="list-inline">
        <?php foreach ($this->container as $page) : ?>
            <?php if (!$page->isActive()) : ?>
                <li>
                    <a href="<?php echo $page->getHref() ?>" title="<?php echo $page->getTitle() ?>">
                        <span <?php echo (!is_null($page->get('label-class'))) ? 'class="' . $page->get('label-class') . '"' : null ?>><?php echo $this->escapeHtml($page->getLabel()) ?></span>
                    </a>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
</div>
