<?php
/**
 * @var Zend\Navigation\Page\Mvc $page
 * @var Zend\Navigation\Page\Mvc $subPage
 */

/** @var Zend\Navigation\Page\Mvc $nav */
$nav = $this->navigation();
$home = $nav->findOneBy('id', 'home');
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $home->getHref() ?>"><?php echo APPLICATION_NAME ?></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <?php foreach ($this->container as $page) : ?>
                    <?php if ($page->isVisible() && $this->layout()->acl->isAllowed($page->getController(), $page->getAction()) && !$page->get('right')) : ?>
                        <?php if ($page->getPages() && $page->get('dropdown') !== false) : ?>
                            <li class="dropdown<?php echo $page->isActive(true) ? ' active' : null ?>">
                                <a id="menu-<?php echo $page->getId() ?>" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" title="<?php echo $page->getTitle() ?>">
                                    <?php echo $page->get('icon') ?>
                                    <span <?php echo (!is_null($page->get('label-class'))) ? 'class="' . $page->get('label-class') . '"' : null ?>><?php echo $this->escapeHtml($page->getLabel()) ?></span>&nbsp;<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <?php foreach ($page as $subPage) : ?>
                                        <?php if ($subPage->isVisible() && $this->layout()->acl->isAllowed($subPage->getController(), $subPage->getAction())) : ?>
                                            <li<?php echo $subPage->isActive(true) ? ' class="active"' : null ?>>
                                                <a id="menu-<?php echo $page->getId() ?>-<?php echo $subPage->getId() ?>" href="<?php echo $subPage->getHref() ?>" title="<?php echo $page->getTitle() ?>">
                                                    <?php echo $subPage->get('icon') ?>
                                                    <span <?php echo (!is_null($subPage->get('label-class'))) ? 'class="' . $subPage->get('label-class') . '"' : null ?>><?php echo $this->escapeHtml($subPage->getLabel()) ?></span>
                                                </a>
                                            </li>
                                        <?php endif ?>

                                    <?php endforeach ?>
                                </ul>
                            </li>
                        <?php else : ?>
                            <li<?php echo $page->isActive(true) ? ' class="active"' : null ?>>
                                <a id="menu-<?php echo $page->getId() ?>" href="<?php echo $page->getHref() ?>" title="<?php echo $page->getTitle() ?>">
                                    <?php echo $page->get('icon') ?>
                                    <span <?php echo (!is_null($page->get('label-class'))) ? 'class="' . $page->get('label-class') . '"' : null ?>><?php echo $this->escapeHtml($page->getLabel()) ?></span>
                                </a>
                            </li>
                        <?php endif ?>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php foreach ($this->container as $page) : ?>
                    <?php if ($page->isVisible() && $this->layout()->acl->isAllowed($page->getController(), $page->getAction()) && $page->get('right')) : ?>
                        <li<?php echo $page->isActive(true) ? ' class="active"' : null ?>>
                            <a id="menu-<?php echo $page->getId() ?>" href="<?php echo $page->getHref() ?>" title="<?php echo $page->getTitle() ?>">
                                <?php echo $page->get('icon') ?>
                                <span <?php echo (!is_null($page->get('label-class'))) ? 'class="' . $page->get('label-class') . '"' : null ?>><?php echo $this->escapeHtml($page->getLabel()) ?></span>
                            </a>
                        </li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</nav>