<?php echo $this->doctype() ?>

<html lang="fr">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(APPLICATION_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?php echo $this->headLink(
            array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            )
        )
        ->prependStylesheet($this->basePath('css/app.min.css')) ?>
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/app.min.js'))
        ->prependFile($this->basePath('js/ie.min.js'), 'text/javascript', array('conditional' => 'lt IE 9')) ?>
</head>
<body>
    <?php echo $this->partial('layout/partial/header') ?>
    <?php echo $this->partial('layout/partial/menu') ?>
    <div class="container">
        <div class="row">
            <div class="col-md-12 page-content">
                <?php echo $this->content ?>
            </div>
        </div>
        <?php echo $this->partial('layout/partial/footer') ?>
        <?php echo $this->inlineScript() ?>
    </div>
</body>
</html>
