<?php
/**
 * @var int $id
 * @var Application\Entity\User $user
 */
echo $this->partial('partial/header', array('id' => $id, 'user' => $user));

?>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 id="identification" class="panel-title"><i class="fa fa-user fa-fw"></i>&nbsp; <?php echo $user->getPrenom() . ' ' . $user->getNom() ?></h3>
        </div>
        <table class="table">
            <tr>
                <th>Email</th>
                <td><?php echo $user->getEmail() ?></td>
            </tr>
            <tr>
                <th>Rôle</th>
                <td><?php echo $user::getStaticRoleList()[$user->getRole()] ?></td>
            </tr>
        </table>
    </div>
</div>