<?php
/**
 * @var int $id
 * @var Application\Form\UserForm $form
 * @var Application\Entity\User $user
 */

echo $this->partial('partial/header', array('id' => $id, 'user' => $user));
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 id="identification" class="panel-title"><i class="fa fa-user fa-fw"></i>&nbsp; Informations personnelles</h3>
        </div>
        <div class="panel-body">
            <?php echo $this->btFormRow($form->get('prenom')) ?>
            <?php echo $this->btFormRow($form->get('nom')) ?>
            <?php echo $this->btFormRow($form->get('email')) ?>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 id="password" class="panel-title"><i class="fa fa-key fa-fw"></i>&nbsp; Mot de passe</h3>
        </div>
        <div class="panel-body">
            <?php echo $this->btFormRow($form->get('password')) ?>
            <?php echo $this->btFormRow($form->get('passwordConfirmation')) ?>
        </div>
    </div>
</div>

<div class="form-group">
    <?php echo $this->formHidden($form->get('id')) ?>
    <ul class="list-inline pull-right">
        <li><?php echo $this->formSubmit($form->get('submit')) ?></li>
    </ul>
</div>

<?php echo $this->form()->closeTag() ?>
