<?php
/**
 * @var Doctrine\Common\Collections\ArrayCollection $users
 * @var Application\Entity\User $user
 * @var Zend\Navigation\Page\Mvc $nav
 */

/** @var \Application\Util\Acl $acl */
$acl = $this->layout()->acl;

echo $this->partial('partial/header-list');

$nav = $this->navigation('Zend\Navigation\Utilisateur');
$items = array('detail', 'edit', 'disable', 'enable', 'delete');
?>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Prénom</th>
        <th>Nom</th>
        <th>Email</th>
        <th>Rôle</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $user->getPrenom() ?></td>
            <td><?php echo $user->getNom() ?></td>
            <td><?php echo $user->getEmail() ?></td>
            <td><?php echo $user::getStaticRoleList()[$user->getRole()] ?></td>
            <td>
                <div class="dropdown pull-right">
                    <a id="dLabel" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Actions
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dLabel">
                        <?php foreach ($items as $action) :
                            /** @var Zend\Navigation\Page\Mvc $item */
                            if ($action == 'disable' || $action == 'enable') {
                                $item = $nav->findOneBy('id', $action);
                                // Vérifie si l'utilisateur est actif /inactif
                                // selon l'action et charge l'item correspondant.
                                if ((($action == 'disable') == $user->isDisabled()) ||
                                    !$acl->isAllowed($item->getController(), $action)
                                ) {
                                    continue;
                                }
                            } else {
                                $item = $nav->findOneBy('id', $action);
                                if (!$this->layout()->acl
                                    ->isAllowed($item->getController(), $item->getAction())
                                ) {
                                    continue;
                                }
                            }
                            $item->setParams(array('id' => $user->getId())) ?>
                            <li>
                                <a href="<?php echo $item->getHref() ?>" title="<?php echo $item->getTitle() ?>">
                                    <?php echo $item->get('icon') . $item->getLabel() ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>