<?php
/**
 * @var int $id
 * @var Application\Entity\Utilisateur $utilisateur
 */
echo $this->partial('partial/header-detail', array('id' => $id, 'utilisateur' => $utilisateur));

?>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 id="identification" class="panel-title"><i class="fa fa-user fa-fw"></i>&nbsp; <?php echo $utilisateur->getPrenom() . ' ' . $utilisateur->getNom() ?></h3>
        </div>
        <table class="table">
            <tr>
                <th>Email</th>
                <td><?php echo $utilisateur->getEmail() ?></td>
            </tr>
            <tr>
                <th>Rôle</th>
                <td><?php echo $utilisateur::getStaticRoleList()[$utilisateur->getRole()] ?></td>
            </tr>
        </table>
    </div>
</div>