<?php
/**
 * @var Application\Form\LigueForm $form
 */

echo $this->partial('partial/header-liste');

$form->prepare();
?>

<div class="form-transparent">
    <?php echo $this->form()->openTag($form) ?>

    <div class="col-md-6">
        <div class="panel panel-<?php echo sizeof($form->getMessages()) ? 'danger' : 'default' ?>">
            <div class="panel-heading">
                <h3 id="identification" class="panel-title"><i class="fa fa-soccer-ball-o fa-fw"></i>&nbsp; Identification</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->formRow($form->get('nom')) ?>
                <?php echo $this->formRow($form->get('image')) ?>
                <?php //echo $this->formRow($form->get('dateDebut')) ?>
                <?php //echo $this->formRow($form->get('dateFin')) ?>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="form-group">
            <?php echo $this->formHidden($form->get('id')) ?>
            <ul class="list-inline text-right">
                <li><?php echo $this->formSubmit($form->get('submit')) ?></li>
            </ul>
        </div>
    </div>

    <?php echo $this->form()->closeTag() ?>
</div>
