<?php
/**
 * @var int $id
 * @var Application\Entity\Ligue $ligue
 * @var Application\Form\ValidationForm $form
 */

echo $this->partial('partial/header-detail', array('id' => $id));
$form->prepare();
?>

<p>Êtes-vous sûr de vouloir supprimer la ligue <b><?php echo $ligue->getNom() ?></b> ?</p>

<div>
    <?php echo $this->form()->openTag($form) ?>
    <ul class="list-inline">
        <li><?php echo $this->formRow($form->get('no')) ?></li>
        <li><?php echo $this->formRow($form->get('yes')) ?></li>
    </ul>
    <?php echo $this->form()->closeTag() ?>
</div>