<?php
/**
 * @var Application\Form\AuthForm $form
 */

echo $this->partial('partial/header/connexion');
$form->prepare();
?>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="form-signin">
            <?php echo $this->form()->openTag($form) ?>
            <?php echo $this->btFormRow($form->get('email'), array('tag' => 'i', 'class' => 'fa fa-envelope')) ?>
            <?php echo $this->btFormRow($form->get('encryptedPassword'), array('tag' => 'i', 'class' => 'fa fa-key')) ?>
            <?php echo $this->btFormRow($form->get('submit')) ?>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>

<?php
echo $this->partial('partial/nav/connexion');