<?php
/**
 * @var Application\Form\UserForm $form
 */

echo $this->partial('partial/header/connexion');
$form->prepare();
?>

<div class="row">
    <div class="card">
        <?php echo $this->form()->openTag($form) ?>
        <?php echo $this->btFormRow($form->get('prenom')) ?>
        <?php echo $this->btFormRow($form->get('nom')) ?>
        <?php echo $this->btFormRow($form->get('email')) ?>

        <?php echo $this->btFormRow($form->get('password')) ?>
        <?php echo $this->btFormRow($form->get('passwordConfirmation')) ?>

        <?php echo $this->btFormRow($form->get('submit')->setValue('S\'inscrire')) ?>

        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<?php
echo $this->partial('partial/nav/connexion');
