<?php
/**
 * @var Application\Form\AuthForgottenPasswordForm $form
 */

echo $this->partial('partial/header/connexion');
$form->prepare();
?>

<div class="row">
    <div class="card">
        <?php echo $this->form()->openTag($form) ?>
        <?php echo $this->btFormRow($form->get('email'), array('tag' => 'i', 'class' => 'fa fa-envelope')) ?>
        <?php echo $this->btFormRow($form->get('submit')) ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<?php
echo $this->partial('partial/nav/connexion');

