<?php
/**
 * @var Application\Form\ResetPasswordForm $form
 */

echo $this->partial('partial/header/connexion');
$form->prepare();
?>

<div class="row">
    <div class="card">
        <?php echo $this->form()->openTag($form) ?>
        <?php echo $this->btFormRow($form->get('email')) ?>
        <?php echo $this->btFormRow($form->get('password')) ?>
        <?php echo $this->btFormRow($form->get('passwordConfirmation')) ?>
        <?php echo $this->btFormRow($form->get('submit')) ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<?php
echo $this->partial('partial/nav/connexion');
